# Generated by Django 3.1.2 on 2020-10-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0003_auto_20201016_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
