# Generated by Django 3.1.2 on 2020-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0004_auto_20201016_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=-1, max_digits=5),
        ),
    ]
